  $(document).ready(function(){
        $("#btn1").click(function(){
            window.location.replace("file:///home/pthao/thaopt/Inter_Vieted/FirstProject/index.html");
        });
        $("#btn2").click(function(){
            window.location.replace("file:///home/pthao/thaopt/Inter_Vieted/FirstProject/useplugin.html");
        });
        $("#btn3").click(function(){
            window.location.replace("file:///home/pthao/thaopt/Inter_Vieted/FirstProject/datetime.html");
        });
  });