  $(document).ready(function(){
        $("#btn1").click(function(){
            window.location.replace("http://localhost/Inter_Vieted/FirstProject/index.html");
        });
        $("#btn2").click(function(){
            window.location.replace("http://localhost/Inter_Vieted/FirstProject/signup.php");
        });
        $("#btn3").click(function(){
            window.location.replace("http://localhost/Inter_Vieted/FirstProject/datetime.html");
        });
  });